name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Application

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: pdo, pdo_pgsql, mbstring, exif, pcntl, bcmath, gd

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install PHP dependencies
        working-directory: backend
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js dependencies
        working-directory: frontend
        run: npm ci

      - name: Check PHP syntax
        working-directory: backend
        run: find . -name "*.php" -exec php -l {} \;

      - name: TypeScript type check
        working-directory: frontend
        run: npm run type-check

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Deploy to Railway

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railway-app/railway-action@v1
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}
          command: up --detach

  notify:
    needs: [test, deploy]
    runs-on: ubuntu-latest
    if: always()
    name: Notify Status

    steps:
      - name: Notify Success
        if: needs.deploy.result == 'success'
        run: |
          echo "🚀 Deployment successful!"
          echo "Your app is live at: https://your-app.railway.app"

      - name: Notify Failure
        if: needs.deploy.result == 'failure' || needs.test.result == 'failure'
        run: |
          echo "❌ Deployment failed!"
          echo "Check the logs for more information."
