name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test and Build

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: pdo, pdo_pgsql

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install PHP dependencies
        working-directory: backend
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js dependencies
        working-directory: frontend
        run: npm ci

      - name: Check PHP syntax
        working-directory: backend
        run: find . -name "*.php" -exec php -l {} \;

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Test completion
        run: |
          echo "✅ All tests passed!"
          echo "📝 Railway will auto-deploy from main branch"
          echo "🎨 Deploy frontend manually to Vercel with VITE_API_URL"
